#1015 add skip option
objectionary/eo pull request #1066
Opened 2022-08-18 07:07 UTC by OlesiaSub

#1015 
cmd usage: `mvn -Deo.skip=true`
pom.xml usage: add `<skip>true</skip>` to `configuration`

2022-08-18 07:18 UTC, OlesiaSub commented
@yegor256 please check

2022-08-18 08:37 UTC, yegor256 commented
@OlesiaSub how do you know it works? where are the tests?

2022-08-18 09:16 UTC, OlesiaSub commented
@yegor256 oh sorry, I wanted to ask you a question about the tests implementation.
I need to check that _nothing will happen_. The only thing I thought of was writing tests similar to your tests for mojos, setting `skip` to `true` there and checking that nothing was created. Is this ok or is there a better way?

2022-08-18 09:19 UTC, OlesiaSub commented
You can see an example of such test in the latest commit (it's almost fully copied from PullMojoTest ,so it's a draft)

2022-08-18 09:25 UTC, yegor256 commented
@OlesiaSub yes, something like this -- run the mojo and assert that nothing is created

2022-08-18 10:41 UTC, OlesiaSub commented
@yegor256 please check

2022-08-18 11:22 UTC, yegor256 commented
@mximp please review

2022-08-18 14:01 UTC, mximp requested changes

2022-08-18 14:01 UTC, mximp commented on eo-maven-plugin/src/main/java/org/eolang/maven/SafeMojo.java
> +            if (this.skip) {
@OlesiaSub This method now has two `return` points, but should have only 1.

2022-08-18 14:01 UTC, mximp commented
@OlesiaSub please check comments above

2022-08-19 06:57 UTC, OlesiaSub commented on eo-maven-plugin/src/test/java/org/eolang/maven/SkipTest.java
> +                        PullMojo.DIR
For some reason it didn't show any mistakes when I used it locally, but failed multiple times here on pull request. But I made the checks pass here + afaik braces style in PullMojoTest is the same. So could you please clarify why is this braces style wrong?

2022-08-19 07:27 UTC, OlesiaSub commented
@mximp fixed, please check

2022-08-19 08:49 UTC, mximp commented on eo-maven-plugin/src/test/java/org/eolang/maven/SkipTest.java
> +                        PullMojo.DIR
@OlesiaSub According to Checkstyle closing brace should have the same indentation as the line with its opening counterpart (if they're on different lines of course).
I couldn't see the same issue in `PullMojoTests`.

2022-08-19 08:51 UTC, mximp approved these changes

2022-08-19 08:52 UTC, mximp commented
@yegor256 please merge

2022-08-19 08:59 UTC, yegor256 commented
@OlesiaSub usually maven plugins print a message when they are skipped, something like:

```
Execution skipped, due to eo.skip option
```

Would be nice to do the same here

2022-08-19 13:11 UTC, OlesiaSub commented
@mximp I added message lo logger.INFO level
(tests are failing again because of #1069 )

2022-08-19 13:51 UTC, mximp commented
@Karina5005 Did tests started to fail after your changes? What caused this? It seems that these changes should not affect existing tests.

2022-08-19 14:08 UTC, yegor256 commented
@mximp that's because `if a { if b {... } }` is a bad style, I believe. should be `if (a & b)`

2022-08-19 14:33 UTC, mximp commented
It seems more functional failure:
```
Error:  EOorg.EOeolang.RamTest.writesAndReads(long, int, String, int, int, String)[2]  Time elapsed: 0.338 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "hello"
     but: was ""
```

2022-08-19 17:02 UTC, Karina5005 commented
@mximp It happened after my changes, but the problem is not in my logic.
A test that uses `@Execution(CONCURRENT)` crashes. There was no file junit-platform.properties before my changes, so this test didn't really run in parallel (https://stackoverflow.com/questions/50586201/parallel-test-case-execution-with-junit-5). After my changes, it started to really work in parallel.
I think you should ask @andreoss to look at this test, because his changes added `@Execution(CONCURRENT)` (https://github.com/objectionary/eo/commit/7cca6fbe3320faa1151e7a78836114cfc3cba194) and now it started to work concurrent, but crash .

2022-08-21 06:58 UTC, yegor256 commented
@OlesiaSub @mximp it's OK to `@Disabled` the test, if it fails for a reason not related to the feature you are implementing. Of course, a ticket must submitted about this situation.

2022-08-21 06:59 UTC, yegor256 commented
@OlesiaSub see #1069

2022-08-22 10:06 UTC, mximp commented
@OlesiaSub would you please comment out the test?

2022-08-22 14:48 UTC, OlesiaSub commented
@mximp please help, I added `@Disabled` annotation to the test, but now the tests fail due to style violation
```
Checkstyle: eo-runtime/src/test/java/EOorg/EOeolang/RamTest.java[58]: More than 3 parameters (found 6). (ParameterNumberCheck)
```
Even though I didn't modify anything else... do you have any ideas why this happened?

2022-08-22 14:49 UTC, OlesiaSub commented
And I just saw that Yegor experienced the same issue

2022-08-22 15:19 UTC, mximp commented
@OlesiaSub did you synched up with master?

2022-08-22 16:40 UTC, OlesiaSub commented
@mximp I did when I committed the changes. But I saw that this issue was fixed. Tests pass now.

2022-08-23 12:43 UTC, mximp approved these changes

2022-08-23 12:43 UTC, mximp commented
@yegor256 please merge

2022-08-23 14:25 UTC, yegor256 commented
@rultor merge

2022-08-23 14:35 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26567-1224152275)

2022-08-23 14:37 UTC, rultor commented
> @rultor merge

@olesiasub @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/26567-1224152275) (spent 2min)

```
+ docker --version
Docker version 20.10.17, build 100c701
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:objectionary/eo.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z 'export '\''head=git@github.com:objectionary/eo.git'\''' ']'
+ cd ..
+ cat
+ '[' false = true ']'
+ cat
+ chmod a+x entry.sh
+ cat
+ echo 'export '\''head=git@github.com:objectionary/eo.git'\''' ';' 'export '\''pull_id=1066'\''' ';' 'export '\''fork=git@github.com:OlesiaSub/eo.git'\''' ';' 'export '\''fork_branch=1015-skip-option'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=#1015 add skip option'\''' ';' 'export '\''author=yegor256'\''' ';' 'javac -version' ';' 'pdd --file=/dev/null' ';' 'mvn clean install -Pqulice --errors -Dstyle.color=never' ';'
+ sensitive=()
+ rm -rf .gpg
+ cd repo
+ git remote add fork git@github.com:OlesiaSub/eo.git
+ git remote update
Fetching origin
Fetching fork
From github.com:OlesiaSub/eo
 * [new branch]        1015-skip-option   -> fork/1015-skip-option
 * [new branch]        920-architect-meta -> fork/920-architect-meta
 * [new branch]        998-cached-tojos   -> fork/998-cached-tojos
 * [new branch]        architect-meta-parsing-train -> fork/architect-meta-parsing-train
 * [new branch]        master             -> fork/master
+ args=
+ '[' default == default ']'
+ args=' --ff'
+ '[' default == no ']'
+ '[' default == only ']'
+ export BRANCH=__rultor
+ BRANCH=__rultor
++ git show-branch __rultor
++ wc -l
+ '[' 0 -gt 0 ']'
+ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
+ git checkout -B __rultor fork/1015-skip-option
Switched to a new branch '__rultor'
Branch '__rultor' set up to track remote branch '1015-skip-option' from 'fork'.
+ git checkout -B master origin/master
Switched to and reset branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
Your branch is up to date with 'origin/master'.
+ '[' false == true ']'
+ '[' false == true ']'
+ git merge --ff __rultor
Auto-merging eo-maven-plugin/src/main/java/org/eolang/maven/SafeMojo.java
CONFLICT (content): Merge conflict in eo-maven-plugin/src/main/java/org/eolang/maven/SafeMojo.java
Automatic merge failed; fix conflicts and then commit the result.
'cid' file is absent, most probably the Docker container wasn't started correctly
```

2022-08-23 16:25 UTC, mximp commented
@OlesiaSub please check

2022-08-24 15:13 UTC, mximp commented
@yegor256 can we please try to merge again

2022-08-24 15:16 UTC, yegor256 commented
@rultor merge

2022-08-24 15:17 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26567-1225866254)

2022-08-24 15:24 UTC, merged

2022-08-24 15:26 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26567-1225866254) (took me 8min)