1065 add offline mode
objectionary/eo pull request #1098
Opened 2022-08-26 05:11 UTC by Karina5005

https://github.com/objectionary/eo/issues/1065

2022-08-26 05:18 UTC, Karina5005 commented
@mximp I have a problem. 
As discussed, I skipped PullMojo in case of no internet connection. But because of this, there is a problem with the fibonacci test and eo-runtime tests. The eo base classes are not loaded (which is expected if there is no internet connection), so a compilation error occurs. 
In the case of using the skip option (`mvn -Deo.skip=true clean install`), tests in eo-runtime also fall, so maybe this is normal behavior?

2022-08-26 07:44 UTC, yegor256 commented
@MikhailLipanin please, review this one

2022-08-26 07:47 UTC, mximp commented
@Karina5005 for fibonacci test it's probably fine - since it's part of `eo-maven-plugin` module and eo runtime is external to it. 
But why it fails for `eo-runtime` all sources are available right in the module? Could you please advise what files are missing?

2022-08-26 08:12 UTC, mximp requested changes

2022-08-26 09:06 UTC, Karina5005 commented
@mximp Files not found when compiling. For example, here are a few:
```
[ERROR] /home/karina/eo/eo-runtime/src/main/java/org/eolang/Data.java:[30,22] cannot find symbol
  symbol:   class EOfloat
  location: package EOorg.EOeolang
[ERROR] /home/karina/eo/eo-runtime/src/main/java/org/eolang/Data.java:[31,22] cannot find symbol
  symbol:   class EOint
  location: package EOorg.EOeolang
[ERROR] /home/karina/eo/eo-runtime/src/main/java/org/eolang/Data.java:[32,22] cannot find symbol
  symbol:   class EOstring
  location: package EOorg.EOeolang
```

2022-08-29 07:44 UTC, mximp commented
@Karina5005 would the tests fail even objects are located in `~\.eo` folder? EO compilation and tests require external objects. If there is no access to web and required objects were not previously downloaded it's logical that the build is failing.

2022-08-31 09:19 UTC, mximp approved these changes

2022-08-31 09:21 UTC, mximp approved these changes

2022-08-31 09:21 UTC, Karina5005 commented on eo-maven-plugin/src/test/java/org/eolang/maven/AssembleMojoTest.java
> +    private static boolean netIsAvailable() {
@mximp I made it a static method of the SafeMojo class, it seems logical to me, perhaps in the future this function will be needed in other Mojos. I'm right?

2022-08-31 09:22 UTC, Karina5005 commented on eo-maven-plugin/src/it/fibonacci/verify.groovy
> +private static boolean netIsAvailable() {
fixed

2022-08-31 09:22 UTC, Karina5005 commented on eo-maven-plugin/src/main/java/org/eolang/maven/PullMojo.java
> +    private static boolean netIsAvailable() {
fixed

2022-08-31 09:23 UTC, Karina5005 commented on eo-maven-plugin/src/main/java/org/eolang/maven/PullMojo.java
> +            final URL url = new URL("http://www.google.com");
fixed

2022-08-31 09:25 UTC, mximp commented
@yegor256 can we please merge this

2022-08-31 09:31 UTC, Karina5005 commented
@mximp I'm not sure I understand how to run it so that the downloaded files are not deleted.
I tried like this:
```
mvn clean install
mvn test
```
 But the files are not found.
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[366,21] cannot find symbol
  symbol:   class EOnumber$EOpow
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[371,21] cannot find symbol
  symbol:   class EOnumber$EOas_float
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[376,21] cannot find symbol
  symbol:   class EOnumber$EOas_int
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[381,21] cannot find symbol
  symbol:   class EOnumber$EOas_string
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOangle.java:[83,21] cannot find symbol
  symbol:   class EOangle$EOsin
  location: class EOorg.EOeolang.EOmath.EOangle
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOangle.java:[88,21] cannot find symbol
  symbol:   class EOangle$EOcos
  location: class EOorg.EOeolang.EOmath.EOangle
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOrandom.java:[48,21] cannot find symbol
  symbol:   class EOrandom$EOpseudo
  location: class EOorg.EOeolang.EOmath.EOrandom
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOcollections/EOmultimap.java:[206,21] cannot find symbol
  symbol:   class EOmultimap$EOrebuild
  location: class EOorg.EOeolang.EOcollections.EOmultimap
```

2022-08-31 10:37 UTC, mximp commented
@Karina5005 are you trying to build it in parent eo module?
Can you please check your `~/.eo/` folder for those EO files?

2022-08-31 11:14 UTC, yegor256 commented
@Karina5005 a general rules is this: if something doesn't work as expected in the `master` branch, make a new ticket about it and wait. When the issue is resolved in the `master` branch, continue the development in your own branch.

2022-08-31 11:23 UTC, yegor256 commented
@Karina5005 indeed, this scenario fails in `master` (I just checked):

```
$ mvn clean install
$ mvn test
```

I suggest you to make a new ticket about it.

2022-09-20 05:15 UTC, yegor256 commented
@Karina5005 what's up with this one?

2022-09-20 08:06 UTC, Karina5005 commented
@yegor256 The ticket https://github.com/objectionary/eo/issues/1130 is still open, so I can't test properly.

2022-12-09 10:09 UTC, yegor256 commented
@mximp can you please pick this up and finish it somehow please?

2022-12-09 12:26 UTC, mximp commented
@yegor256 I will recreate PR

2022-12-09 12:55 UTC, mximp commented
recreated in https://github.com/objectionary/eo/pull/1550

2022-12-09 12:55 UTC, closed without merging