Added classifier to "+rt" meta
objectionary/eo pull request #1135
Opened 2022-09-01 12:18 UTC by MikhailLipanin

#1010

2022-09-01 14:32 UTC, Graur requested changes
@MikhailLipanin Good one! I suggest just one minor fix

2022-09-01 14:32 UTC, Graur commented on eo-maven-plugin/src/main/java/org/eolang/maven/ResolveMojo.java
> +        }
@MikhailLipanin Can we simplify this part? Just by calculating the `classifier` and pass it to `String.format`

2022-09-01 15:56 UTC, Graur approved these changes
@yegor256 please, have a look

2022-09-02 12:17 UTC, yegor256 commented
@rultor hello

2022-09-02 12:18 UTC, rultor commented
> @rultor hello

@yegor256 Hi there! I understand a few simple commands: "merge", "deploy", etc. [This page](https://doc.rultor.com/basics.html) explains them briefly. Any questions or bug reports are [welcome](https://github.com/yegor256/rultor/issues). Have fun :)

2022-09-02 12:19 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26661-1235433154)

2022-09-02 12:23 UTC, merged

2022-09-02 12:24 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26661-1235433154) (took me 5min)