1299 double dataization
objectionary/eo pull request #1340
Opened 2022-10-15 16:17 UTC by includealex

Closes #1299

2022-10-15 16:25 UTC, includealex commented
@Graur please take a look.

2022-10-16 12:52 UTC, includealex commented
@levBagryansky please take a look.

2022-10-16 12:53 UTC, levBagryansky commented
@includealex sure

2022-10-16 13:04 UTC, levBagryansky requested changes
@includealex Do we realy need to check `stdout`?

2022-10-16 13:20 UTC, levBagryansky commented
@includealex May be it would be better to implemet the test in java if you want to check `stdout`? Look at [this](https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/java/EOorg/EOeolang/EOintEOminusTest.java) to understand how to use eo objects in java

2022-10-17 09:53 UTC, Graur requested changes

2022-10-17 09:53 UTC, Graur commented on .gitignore
> +.factorypath
@includealex Why do we need this change?

2022-10-20 17:18 UTC, includealex commented
@levBagryansky please take a look

2022-10-20 17:31 UTC, levBagryansky approved these changes
@includealex looks good as for me

2022-10-20 17:37 UTC, includealex commented
@yegor256 please take a look

2022-10-20 17:41 UTC, Graur requested changes

2022-10-20 17:41 UTC, Graur commented on eo-runtime/src/test/java/EOorg/EOeolang/EOseqTest.java
> -
@includealex Do we really need this change?

2022-10-20 17:41 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/single_dataization-tests.eo
> +# @todo #1299:60min Implement test that will
@includealex this `@todo` will fail `pdd` check. Can you add an extra space between text and `#` on each line after the first line?

2022-10-20 18:46 UTC, includealex commented
@Graur please check it.

2022-10-21 07:27 UTC, Graur approved these changes
@yegor256 please, have a look

2022-10-22 08:41 UTC, includealex commented
@yegor256 please take a look

2022-10-22 09:02 UTC, yegor256 commented
@includealex please, see how all other test files are named in `src/test/eo` and make sure your tests are placed right

2022-10-22 13:30 UTC, includealex commented
@yegor256 please have a look

2022-10-23 14:53 UTC, includealex commented
@yegor256 please take a look

2022-10-26 15:26 UTC, yegor256 commented
@rultor merge

2022-10-26 15:29 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/27667-1292222985)

2022-10-26 15:36 UTC, merged

2022-10-26 15:37 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/27667-1292222985) (took me 8min)