added number of threads used in thread executor within exec() method
objectionary/eo pull request #1369
Opened 2022-10-26 09:02 UTC by holydrug

2022-10-26 10:05 UTC, mximp commented
@holydrug PR should contain issue reference in the description. This way it's automatically linked to the issue.

2022-10-26 10:10 UTC, mximp commented on eo-maven-plugin/src/main/java/org/eolang/maven/ParseMojo.java
> +     * @checkstyle MemberNameCheck (7 lines)
@holydrug I believe this suppression is redundant.

2022-10-26 10:10 UTC, mximp commented on eo-maven-plugin/src/main/java/org/eolang/maven/ParseMojo.java
> +     * Default threads number.
@holydrug This parameter is not for _default threads number_ but rather for just number of parallel threads.

2022-10-26 16:02 UTC, holydrug commented
@mximp review please.

2022-10-27 06:07 UTC, mximp commented
@holydrug you have deleted wrong suppression: I was referring to Checkstyle

2022-10-27 06:08 UTC, mximp requested changes

2022-10-27 06:08 UTC, mximp commented on eo-maven-plugin/src/main/java/org/eolang/maven/ParseMojo.java
> +    private int threads = 4;
@holydrug PMD suppression should remain

2022-10-27 08:08 UTC, holydrug commented
@mximp review please.

2022-10-27 10:24 UTC, mximp approved these changes

2022-10-27 10:24 UTC, mximp commented
@yegor256 please merge

2022-11-02 08:46 UTC, mximp commented
@yegor256 reminder

2022-11-02 10:03 UTC, yegor256 commented
@rultor merge

2022-11-02 10:04 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/27792-1299973760)

2022-11-02 10:10 UTC, merged

2022-11-02 10:11 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/27792-1299973760) (took me 7min)