set locators for all objects in XMIR
objectionary/eo pull request #1462
Opened 2022-11-17 11:58 UTC by yegor256

I added an extra attribute to all XMIR objects. The attribute contains unique locator of an object.

2022-11-17 15:50 UTC, volodya-lombrozo requested changes
@yegor256 I believe we need more test cases here.

2022-11-17 15:50 UTC, volodya-lombrozo commented on eo-parser/src/main/resources/org/eolang/parser/set-locators.xsl
> +            <xsl:when test="name($o) = 'o'">
@yegor256 Could it be something except object `<o>` here?

2022-11-17 19:07 UTC, yegor256 commented
@volodya-lombrozo very good catch! I added more tests and extra validation, please check again.

2022-11-18 08:02 UTC, volodya-lombrozo requested changes
@yegor256 only one question about `ν0`. You can also squash commits to make the history more clear.

2022-11-18 08:02 UTC, volodya-lombrozo commented on eo-parser/src/main/resources/org/eolang/parser/set-locators.xsl
> +              <xsl:text>ν0</xsl:text>
@yegor256 Please, provide an example, where we can receive the `ν0`

2022-11-18 09:09 UTC, yegor256 commented
@volodya-lombrozo you are right again, thanks! I removed the redundant piece of code, check 869ed32d

2022-11-18 12:26 UTC, yegor256 commented
@rultor merge

2022-11-18 12:27 UTC, yegor256 commented
@volodya-lombrozo `Φ.org.abc.tt.α2.φ` is the locator or `hello`. I will explain you this in person, it's a long story :)

2022-11-18 12:48 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/28606-1319932101)

2022-11-18 13:08 UTC, merged

2022-11-18 13:09 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/28606-1319932101) (took me 20min)