Prohibit non zero versions for dev sources
objectionary/eo pull request #1795
Opened 2023-02-13 14:37 UTC by mximp

closes #854

2023-02-13 14:39 UTC, mximp commented
@volodya-lombrozo please review

2023-02-13 14:57 UTC, volodya-lombrozo requested changes
@mximp 

1. Maybe we can implement that check using `xlst`? I mean we can add just one more check to `eo-parser/src/main/resources/org/eolang/parser/errors`.

2. The tests is hard to read because they are using `xml` concatenation. Maybe we can use something like [this](https://github.com/objectionary/eo/blob/master/eo-parser/src/test/java/org/eolang/parser/PacksTest.java)?

2023-02-13 15:52 UTC, mximp commented
@volodya-lombrozo Thanks for the hint! Made it with XSLT.
Please recheck

2023-02-13 17:16 UTC, volodya-lombrozo requested changes

2023-02-13 17:16 UTC, volodya-lombrozo commented on eo-parser/src/main/resources/org/eolang/parser/errors/zero-version.xsl
> +        <xsl:if test="matches($src, 'src/(?:main|test)') and not(./tail/text() = '0.0.0')">
@mximp The only thing which isn't clear it's why exactly `main|test`? 

I've found your comment: 

> The policy is not to update the version manually.
It should always be 0.0.0 in master and development branches.
It's incremented automatically during deployment process.

Why then it isn't a `master|test` ?

2023-02-14 15:07 UTC, volodya-lombrozo requested changes
@mximp I got it, thank you. Everything looks good to me, but can I ask you to rename tests, please:
```
zero-version-correct-version.yml -> zero-version-for-main-correct.yml
zero-version-for-test.yml -> zero-version-for-test-wrong.yaml
zero-version-no-version.yml -> good
zero-version-no-version-not-applicable-source.yml -> good
zero-version.yml -> zero-version-for-main-wrong.yml
```
I was trying to understand which cases you considered and it take some time to understand.

2023-02-14 15:33 UTC, mximp commented
@volodya-lombrozo please check now

2023-02-14 15:38 UTC, volodya-lombrozo approved these changes
@mximp Thanks. Looks good to me.
@yegor256 Could you merge that changes, please?

2023-02-16 08:59 UTC, mximp commented
@yegor256 please merge the PR

2023-02-16 09:27 UTC, yegor256 commented
@rultor merge

2023-02-16 09:29 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/30236-1432779193)

2023-02-16 09:37 UTC, merged

2023-02-16 09:38 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/30236-1432779193) (took me 8min)