1809 presence of version meta
objectionary/eo pull request #1811
Opened 2023-02-17 15:26 UTC by levBagryansky

resolves #1809

2023-02-17 15:35 UTC, levBagryansky commented
@Graur please review

2023-02-17 21:14 UTC, levBagryansky commented
@MikhailLipanin please review

2023-02-18 18:52 UTC, MikhailLipanin requested changes

2023-02-18 18:52 UTC, MikhailLipanin commented on eo-parser/src/main/java/org/eolang/parser/ParsingTrain.java
> +        "/org/eolang/parser/warnings/mandatory-version-meta.xsl",
We need to add `incorrect-version.xsl` to this pipeline too, like `incorrect-home` and `incorrect-architect.xsl`

2023-02-19 11:21 UTC, MikhailLipanin approved these changes
@levBagryansky Looks good to me,
@yegor256 can you merge?

2023-02-20 06:44 UTC, levBagryansky commented
@yegor256 please take a look

2023-02-20 06:55 UTC, Graur approved these changes

2023-02-20 07:22 UTC, yegor256 commented
@rultor merge

2023-02-20 07:24 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/30304-1436471954)

2023-02-20 07:32 UTC, merged

2023-02-20 07:34 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/30304-1436471954) (took me 10min)