#1824 Make `+inf.times` and `-inf.times` work with multiple arguments
objectionary/eo pull request #1843
Opened 2023-02-25 14:58 UTC by maxonfjvipon

Closes: #1824 

What's done:
- Made `positive-infinity.times` work with multiple arguments
- Made `negative-infinity.times` work with multiple arguments
- Added tests
- Added `todo` for future optimization

2023-02-25 15:05 UTC, maxonfjvipon commented
@Graur please have a look

2023-02-27 08:11 UTC, Graur requested changes
@maxonfjvipon Good one, just one comment from my side

2023-02-27 08:11 UTC, Graur commented on eo-runtime/src/main/eo/org/eolang/positive-infinity.eo
> +    #  more objects-functions to another object. To avoid code duplication
@maxonfjvipon As far as I understand this todo issue, you want to provide to the object more than 3 arguments. If it's it right you can just add all your arguments to new array and pass this array as argument to particular object

2023-02-27 11:36 UTC, maxonfjvipon commented
@Graur could you please review one more time and check what's wrong with windows build

2023-03-01 23:58 UTC, maxonfjvipon commented
@Graur please have a look one more time

2023-03-03 12:12 UTC, maxonfjvipon commented
@yegor256 please have a look

2023-03-03 14:38 UTC, yegor256 commented
@rultor merge

2023-03-03 14:49 UTC, merged

2023-03-03 14:50 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/30514-1453627929) (took me 10min)