1327 binarizemojo test
objectionary/eo pull request #1858
Opened 2023-02-28 21:21 UTC by levBagryansky

A test enviromonet for `BinarizeMojo`

2023-03-01 14:45 UTC, levBagryansky commented
@Graur please review

2023-03-01 15:15 UTC, Graur requested changes

2023-03-01 17:15 UTC, levBagryansky commented on eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java
> +    public static final String DIR = "binarize/";
@Graur `binarize` and `binarize/` mean the same directory. Is it incorrect?

2023-03-02 08:20 UTC, Graur approved these changes
@levBagryansky Looks good to me, thanks!
@yegor256 Please, have a look

2023-03-02 16:31 UTC, levBagryansky commented
@yegor256 please take a look

2023-03-02 22:20 UTC, yegor256 commented
@levBagryansky this is not a fully working implementation, is it? I guess, you should add a puzzle to your code, so that a ticket will be created when we merge the PR

2023-03-03 10:44 UTC, levBagryansky commented
@yegor256 please take a look

2023-03-03 11:52 UTC, yegor256 commented
@rultor merge

2023-03-03 11:54 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/30511-1453417962)

2023-03-03 12:02 UTC, merged

2023-03-03 12:02 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/30511-1453417962) (took me 8min)