1900 dependencies dependencies to rust sections
objectionary/eo pull request #1908
Opened 2023-03-16 13:26 UTC by levBagryansky

Closes: #1900 
Creates a new section `<dependencies>` with `dependency`s inside. The result XML looking like that:
```
...
  <rusts>
      <rust code="75 73 65 20 72 65 6F 3A 3.."
            loc="Φ.org.eolang.creates-object.r">
         <dependencies>
            <dependency name="72 65 6F 3A 20 30 2E 30 2E 32"/>
            <dependency name="72 61 6E 64 3A 20 30 2E 35 2E 35"/>
         </dependencies>
      </rust>
   </rusts>
</program>
```

2023-03-16 14:14 UTC, levBagryansky commented
@Graur please review. There are build failures because of math in eo-runtime

2023-03-17 09:31 UTC, levBagryansky commented
@Graur please take a look.

2023-03-17 10:42 UTC, Graur requested changes

2023-03-17 10:42 UTC, Graur commented on eo-maven-plugin/src/main/resources/org/eolang/maven/add_rust/add_rust.xsl
> +                <xsl:for-each select="../o/o">
@levBagryansky I believe searching the parent node attribute has separate value. Something like this:
```
<xsl:for-each select="ancestor::o[1]/@o">
```

2023-03-17 10:42 UTC, Graur commented on eo-maven-plugin/src/main/resources/org/eolang/maven/add_rust/add_rust.xsl
> +                  <xsl:if test="../attribute(base) = 'org.eolang.tuple' and attribute(base) = 'org.eolang.string'">
@levBagryansky Same here. I believe we can replace `..` by `parent::@base`. Or something similar to this approach

2023-03-17 12:01 UTC, Graur approved these changes
@levBagryansky Looks good to me, thanks!
@yegor256 Please, take a look

2023-03-18 07:33 UTC, levBagryansky commented
@yegor256 please take a look

2023-03-18 14:15 UTC, levBagryansky commented
@yegor256 please check

2023-03-18 23:59 UTC, yegor256 commented
@rultor merge

2023-03-19 00:17 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/30862-1475037814)

2023-03-19 00:31 UTC, merged

2023-03-19 00:33 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/30862-1475037814) (took me 16min)