feat(#1820): remove tuple.empty object
objectionary/eo pull request #1975
Opened 2023-04-04 14:45 UTC by volodya-lombrozo

Remove `tuple.empty` object.

Closes: #1820

2023-04-04 14:46 UTC, volodya-lombrozo commented
@Graur could you have a look, please?

2023-04-04 15:51 UTC, Graur commented
@volodya-lombrozo  As far as I know, you may be able to create a `tuple` object by simply calling its name. Like:

```
[] > test
  tuple > a
  a.with 3 > @
```

Looks like this pull request can't solve this issue

2023-04-12 08:51 UTC, volodya-lombrozo commented
@Graur The PR is ok now, could you take a look, again, please?

2023-04-17 07:46 UTC, Graur commented
@volodya-lombrozo One possible way is to create `@` atom inside `tuple` object. Like the following:

```
[] > tuple
  [] > @ /?
...
```
and implement empty array initialisation logic in `EOtuple$EO@.java` class

Or maybe it will be possible to create an empty array in runtime. E.g. in `to-java.xsl`.

2023-04-19 08:59 UTC, volodya-lombrozo commented
Non of the next improvements don't help:
```
[] > tuple
  [] > @ /?
...
```
or
```
[] > tuple
  * > @
...
```
or
```
[] > tuple
  [] > @
    * > @
```

2023-04-19 09:17 UTC, Graur requested changes
@volodya-lombrozo Indeed, triggering the creation of a `tuple` object at runtime was a bad idea on my part.

2023-04-19 09:17 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/tuple-tests.eo
> +  *
@volodya-lombrozo Should `tuple` be here?

2023-04-19 09:21 UTC, volodya-lombrozo commented
@Graur Could you take a look again, please?

2023-04-19 10:39 UTC, Graur approved these changes
@volodya-lombrozo I like this solution!
@yegor256 Please, have a look

2023-04-19 11:18 UTC, volodya-lombrozo commented
@yegor256 Could you merge that changes, please?

2023-04-19 11:29 UTC, yegor256 commented
@rultor merge

2023-04-19 11:32 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/31566-1514570846)

2023-04-19 11:41 UTC, merged

2023-04-19 11:41 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/31566-1514570846) (took me 10min)