1965 two mojo
objectionary/eo pull request #1984
Opened 2023-04-07 10:13 UTC by levBagryansky

Improved #1983

2023-04-07 10:31 UTC, levBagryansky commented
@Graur please review

2023-04-07 10:53 UTC, levBagryansky commented
@Graur tests with infinity failed again

2023-04-07 11:07 UTC, Graur commented
> @Graur tests with infinity failed again

They are flaky, so just rerun github checks again by commiting something in your branch

2023-04-07 11:53 UTC, Graur requested changes
@levBagryansky Good one, just a few comments below

2023-04-07 11:53 UTC, Graur commented on eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeParseMojo.java
> +        final StringBuilder out = new StringBuilder(1 + 5 * loc.length());
@levBagryansky Can we give a certain name to these `magic numbers`: `1 + 5`?

2023-04-07 11:53 UTC, Graur commented on eo-maven-plugin/src/main/java/org/eolang/maven/rust_project/BuildFailureException.java
> +public class BuildFailureException extends RuntimeException {
@levBagryansky I like this new Exception you are created!

2023-04-07 11:53 UTC, Graur commented on eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeMojoTest.java
> +    void parsesSimpleEoProgram(@TempDir final Path temp) throws Exception {
@levBagryansky Compound name is too heavy, maybe we can cal it just `parse`? According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

2023-04-07 14:02 UTC, levBagryansky commented
@Graur please check

2023-04-07 14:09 UTC, Graur approved these changes
@levBagryansky Looks good to me, thanks!
@yegor256 Please, have a look

2023-04-07 19:06 UTC, levBagryansky commented
@yegor256 please check

2023-04-08 02:19 UTC, yegor256 commented
@levBagryansky no test for this new mojo? why?

2023-04-08 09:26 UTC, levBagryansky commented
@yegor256 please check. I trasferred tests related to new mojo from `BinarizeMojoTest` into new class.

2023-04-10 07:16 UTC, levBagryansky commented
@yegor256 please take a look

2023-04-10 07:21 UTC, yegor256 commented
@rultor merge

2023-04-10 07:23 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/31387-1501493505)

2023-04-10 07:32 UTC, merged

2023-04-10 07:33 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/31387-1501493505) (took me 10min)