refactor(#1989):  Remove ATTR_* from Mojos
objectionary/eo pull request #2005
Opened 2023-04-18 11:29 UTC by volodya-lombrozo

1. Remove ATTR_* from all Mojos
2. Rename and simplify methods 
3. Puzzle is added for `binarizesWithoutErrors` test

2023-04-18 11:31 UTC, volodya-lombrozo commented
@Graur Could you have a look, please?

2023-04-18 14:53 UTC, Graur requested changes

2023-04-19 08:03 UTC, Graur approved these changes
@volodya-lombrozo Looks good to me
@yegor256 Please, have a look

2023-04-19 08:04 UTC, volodya-lombrozo commented on eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeMojoTest.java
> +     *  {@link org.eolang.maven.OnlineCondition}.
@Graur I suggest ignoring tests for Rust only if it is not installed on the working system.

2023-04-19 11:17 UTC, volodya-lombrozo commented
@yegor256 Could you merge that changes, please?

2023-04-19 11:55 UTC, Graur approved these changes

2023-04-20 07:14 UTC, volodya-lombrozo commented
@yegor256 Could you merge that changes, please?

2023-04-20 14:26 UTC, volodya-lombrozo commented
@yegor256 Reminder

2023-04-21 06:06 UTC, volodya-lombrozo commented
@yegor256 Reminder

2023-04-21 08:46 UTC, yegor256 commented
@rultor merge

2023-04-21 08:48 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/31617-1517490254)

2023-04-21 08:57 UTC, merged

2023-04-21 08:57 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/31617-1517490254) (took me 10min)