feat(#2125): add OyFilesystemSources class
objectionary/eo pull request #2127
Opened 2023-06-05 09:46 UTC by volodya-lombrozo

Add OyFilesystemSources class for testing purposes.

Closes #2125

2023-06-05 09:47 UTC, volodya-lombrozo commented
@mximp Could you have a look, please?

2023-06-05 11:48 UTC, mximp requested changes
@volodya-lombrozo I strongly believe that implemented functionality must be covered with tests. Otherwise (even with puzzle) we decrease quality of code within master branch.

2023-06-05 11:48 UTC, mximp commented on eo-maven-plugin/src/main/java/org/eolang/maven/objectionary/OyFilesystemSources.java
> +public final class OyFilesystemSources implements Objectionary {
@volodya-lombrozo Does it really imply multiple sources per instance? Maybe `OyFilesystem` is better?

2023-06-05 13:03 UTC, volodya-lombrozo commented
@mximp As for tests - They will be implemented in the next puzzle. We can do it because the OyFilesystem is already being used in other tests, which proves the correct functioning of the class. Moreover, if you check the code coverage, you will see that it remains unchanged. Thus, we can conclude that the quality level remains the same. Tests here are required more for understanding the behavior of the class. It's just an enhancement.

2023-06-05 15:20 UTC, volodya-lombrozo commented
@yegor256 Could you merge that changes, please?

2023-06-06 00:02 UTC, yegor256 commented
@rultor merge

2023-06-06 00:04 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/32449-1577707079)

2023-06-06 00:17 UTC, merged

2023-06-06 00:18 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/32449-1577707079) (took me 13min)