2195 cargos
objectionary/eo pull request #2202
Opened 2023-07-03 15:32 UTC by levBagryansky

Closes: #2195 
Create separate cargo project for every rust insert.

2023-07-03 16:46 UTC, levBagryansky commented
@Graur please review. Sems there were troubles with connection in windows test: 
```
Error: [ERROR] There was an error in compilation
Warning:  >>     Updating crates.io index
Warning: [WARNING] >> warning: spurious network error (3 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
Warning: [WARNING] >> warning: spurious network error (2 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
Warning: [WARNING] >> warning: spurious network error (1 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
Warning:  >> error: failed to get `syn` as a dependency of package `thiserror-impl v1.0.40`
Warning:  >>     ... which satisfies dependency `thiserror-impl = "=1.0.40"` of package `thiserror v1.0.40`
Warning:  >>     ... which satisfies dependency `thiserror = "^1.0.20"` of package `jni v0.21.1`
Warning:  >>     ... which satisfies dependency `jni = "^0.21.1"` of package `common v0.1.0 (D:\a\eo\eo\eo-runtime\target\eo-test\Lib\dxxaxeoxeoxeoxruntimextargetxeoxtest0)`
Warning:  >> 
Warning:  >> Caused by:
Warning:  >>   failed to query replaced source registry `crates-io`
Warning:  >> 
Warning:  >> Caused by:
Warning:  >>   download of 3/s/syn failed
Warning:  >> 
Warning:  >> Caused by:
Warning:  >>   failed to download from `[https://index.crates.io/3/s/syn`](https://index.crates.io/3/s/syn%60)
Warning:  >> 
Warning:  >> Caused by:
Warning:  >>   [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
Error:  Failed to build cargo project with dest = D:\a\eo\eo\eo-runtime\target\eo-test\Lib\dxxaxeoxeoxeoxruntimextargetxeoxtest0
```

2023-07-04 08:07 UTC, levBagryansky commented
@Graur please take a look

2023-07-04 08:22 UTC, Graur requested changes
@levBagryansky Good one! Just a few comments from my side:

2023-07-04 08:22 UTC, Graur commented on eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java
> +                    final ByteArrayOutputStream stdout = new ByteArrayOutputStream();
@levBagryansky Same here. Looks like we can inline this variable. According to: https://www.yegor256.com/2015/09/01/redundant-variables-are-evil.html

2023-07-04 09:29 UTC, Graur approved these changes
@levBagryansky Looks good to me
@yegor256 Could you please have a look?

2023-07-04 11:45 UTC, levBagryansky commented
@yegor256 please take a look

2023-07-04 14:10 UTC, levBagryansky commented
@yegor256 please check

2023-07-04 18:10 UTC, levBagryansky commented
@yegor256 could you please merge these changes?

2023-07-04 18:13 UTC, yegor256 commented
@rultor merge

2023-07-04 18:16 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/33126-1620597284)

2023-07-04 18:26 UTC, merged

2023-07-04 18:27 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/33126-1620597284) (took me 11min)