2237 rust side
objectionary/eo pull request #2286
Opened 2023-07-20 14:57 UTC by levBagryansky

Closes #2237

---

## PR-Codex overview
### Focus of this PR:
This PR focuses on implementing new methods in the `EOEnv` Rust struct and the corresponding Java class `EOrust` to enable data manipulation in EO objects.

### Detailed summary:
- Implemented the `put` method in `EOEnv` to store data in EO objects.
- Implemented the `bind` method in `EOEnv` to establish a parent-child relationship between EO objects.
- Implemented the `copy` method in `EOEnv` to create a copy of an EO object.
- Added placeholder code for the `dataize` method in `EOEnv` to convert EO object data into a byte array.
- Added placeholder code for the `put`, `bind`, and `copy` methods in the `EOrust` Java class.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-07-20 15:17 UTC, levBagryansky commented
@Graur please review

2023-07-20 15:58 UTC, Graur requested changes

2023-07-20 16:02 UTC, levBagryansky commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
> +  nop > @
@Graur Indeed we can enable it

2023-07-20 16:21 UTC, Graur approved these changes
@levBagryansky Looks good to me, thanks!
@yegor256 Please have a look

2023-07-21 08:53 UTC, levBagryansky commented
@yegor256 could you please merge these changes?

2023-07-21 12:22 UTC, yegor256 commented
@rultor merge

2023-07-21 12:37 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/33436-1645497972)

2023-07-21 12:48 UTC, merged

2023-07-21 12:48 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/33436-1645497972) (took me 11min)