2313 universe
objectionary/eo pull request #2316
Opened 2023-07-25 14:08 UTC by levBagryansky

Closes: #2313

2023-07-25 14:31 UTC, levBagryansky commented
@Graur please take a look

2023-07-25 15:42 UTC, Graur reviewed
@levBagryansky Just to be sure: You take some part from `EOrust` class and put it to new `Universe.class`?

2023-07-25 16:11 UTC, levBagryansky commented
Yes, this functionality must be in other class.

2023-07-25 19:45 UTC, Graur requested changes
@levBagryansky Good one, just a few suggestions below:

2023-07-25 19:45 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Universe.java
> +    public void put(final int vertex, final byte[] bytes) {
@levBagryansky You need to add something here to avoid style checkers failings

2023-07-25 19:45 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Universe.java
> +    public void bind(final int parent, final int child, final String att) {
@levBagryansky You need to add something here to avoid style checkers failings

2023-07-25 19:45 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Universe.java
> +    private final Phi connector;
@levBagryansky Looks like it is better to use this field to avoid style checker's warning

2023-07-26 11:11 UTC, Graur approved these changes
@levBagryansky Good one
@yegor256 Please have a look

2023-07-26 14:37 UTC, levBagryansky commented
@yegor256 please check

2023-08-13 12:08 UTC, levBagryansky commented
@yegor256 please check

2023-08-13 12:19 UTC, yegor256 commented
@rultor merge

2023-08-13 12:21 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/34176-1676343252)

2023-08-13 12:32 UTC, merged