#1307 Types in runtime
objectionary/eo pull request #2325
Opened 2023-07-27 18:16 UTC by maxonfjvipon

Ref: #1307

2023-07-27 18:56 UTC, maxonfjvipon commented
@yegor256 please have a look

2023-07-28 08:18 UTC, maxonfjvipon commented
@Graur please review this one

2023-07-28 10:20 UTC, Graur requested changes

2023-07-28 10:28 UTC, maxonfjvipon commented on eo-runtime/src/test/java/org/eolang/PhDefaultTest.java
> +        Phi five = new EOint(Phi.Φ);
@Graur sure

2023-07-28 10:29 UTC, maxonfjvipon commented
@Graur please have a look one more time

2023-07-28 10:35 UTC, Graur approved these changes
@maxonfjvipon Good one
@yegor256 Please have a look

2023-07-28 11:20 UTC, maxonfjvipon commented
@yegor256 please have a look

2023-07-28 11:26 UTC, yegor256 commented
@rultor merge

2023-07-28 12:10 UTC, merged

2023-07-28 12:11 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/33648-1655524436) (took me 11min)