2280 universe find and dataize
objectionary/eo pull request #2385
Opened 2023-08-13 20:10 UTC by levBagryansky

2023-08-13 20:46 UTC, levBagryansky commented
@Graur could you please review these changes?

2023-08-14 07:58 UTC, Graur requested changes
@levBagryansky Good one!

2023-08-14 07:58 UTC, Graur commented on eo-runtime/src/test/java/org/eolang/UniverseTest.java
> +        );
@levBagryansky Maybe it would be better to make it shorter? Not three lines of code, but only one. Or inline `phi` object. It is up to you.

2023-08-14 07:58 UTC, Graur commented on eo-runtime/src/test/java/org/eolang/UniverseTest.java
> +        final Universe universe = new Universe(
@levBagryansky Same here

2023-08-14 09:09 UTC, Graur approved these changes
@levBagryansky Good one
@yegor256 Please take a look

2023-08-14 14:17 UTC, levBagryansky commented
@yegor256 please check

2023-08-16 08:56 UTC, levBagryansky commented
@yegor256 please take a look

2023-08-16 18:45 UTC, yegor256 commented
@rultor merge

2023-08-16 23:42 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/34253-1681107822)

2023-08-16 23:53 UTC, merged

2023-08-16 23:54 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/34253-1681107822) (took me 12min)