jaxec instead of VerboseProcess
objectionary/eo pull request #2459
Opened 2023-08-30 19:37 UTC by yegor256

Jaxec library is now used instead of `VerboseProcess` from jcabi-log

2023-08-31 09:36 UTC, yegor256 commented
@volodya-lombrozo please, check

2023-09-01 05:04 UTC, yegor256 commented
@volodya-lombrozo ping

2023-09-01 08:00 UTC, volodya-lombrozo requested changes
@yegor256 Could you please assign your PR to an issue which you are trying to solve?
For example, you can add one of the [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by issue number.

2023-09-01 08:00 UTC, volodya-lombrozo commented on eo-parser/src/test/java/org/eolang/parser/XMIRTest.java
> +        new Jaxec(
@yegor256 What do you think if we test this in a separate unit test? It looks like a clear example of `Cuckoo` anti-pattern:
https://www.yegor256.com/2018/12/11/unit-testing-anti-patterns.html

2023-09-01 09:39 UTC, volodya-lombrozo commented
@yegor256 What about other comments?

2023-09-01 10:42 UTC, yegor256 commented
@volodya-lombrozo updated and answered, see above

2023-09-01 11:52 UTC, volodya-lombrozo requested changes
@yegor256 I've finally read the entire method that you are trying to extend. I noticed, based on the method's comment, that it might not be best placed here. It's a bit puzzling how this method found its way here, but that's okay. 
While reviewing, I observed that this method aligns with a few anti-patterns, such as:
* Giant
* Free Ride
* Excessive Setup
* (Maybe more)
https://www.yegor256.com/2018/12/11/unit-testing-anti-patterns.html

How about we consider adding a task or a puzzle to possibly refactor this test? Or, if it makes sense, we might think of replacing it with a more suitable CI pipeline. 
___
Also I just wanted to point out something regarding the issue title of this PR - "jaxec instead of VerboseProcess." From what I observed, we still have instances of `VerboseProcess` in both `BinarizeMojo` and `SnippetTestCase`.
Might I suggest that we consider adding a task or a puzzle to address replacing those instances as well? Just to ensure consistency throughout our codebase.

2023-09-01 13:56 UTC, volodya-lombrozo approved these changes
@yegor256 Looks good to me, thank you. 
I created the separate [issue](https://github.com/objectionary/eo/issues/2464) to solve the problem with `XMIRTest#convertsAntlrToEbnf()` method.

2023-09-01 14:17 UTC, yegor256 commented
@rultor merge

2023-09-01 14:19 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/34651-1702821791)

2023-09-01 14:32 UTC, merged

2023-09-01 14:33 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/34651-1702821791) (took me 13min)