#2509: Make it to return Option<EO> instead of just EO
objectionary/eo pull request #2510
Opened 2023-09-27 19:31 UTC by levBagryansky

2023-09-28 08:11 UTC, levBagryansky commented
@Graur please check

2023-10-01 18:57 UTC, levBagryansky commented
@Graur please check

2023-10-02 08:13 UTC, Graur requested changes

2023-10-02 08:13 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
> +      let _bytes = env.dataize(v)?;
@levBagryansky Should there also be 4 spaces missing at the beginning of the line with the code?

2023-10-02 08:13 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
> +      env.bind(v1 , v2, "EO-att")?;
@levBagryansky Should there also be 4 spaces missing at the beginning of the line with the code?

2023-10-02 08:13 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
> +      Some(EOError("Custom error".to_string()))
@levBagryansky Should there also be 4 spaces missing at the beginning of the line with the code?

2023-10-02 08:13 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
> +      env.put(copy.clone(), &[0x00, 0x1a, 0xEE])?;
@levBagryansky Should there also be 4 spaces missing at the beginning of the line with the code?

2023-10-02 08:13 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
> +      Some(EOVertex(copy))
@levBagryansky Should there also be 4 spaces missing at the beginning of the line with the code?

2023-10-02 10:53 UTC, Graur approved these changes
@levBagryansky Looks good to me!
@yegor256 Please have a look

2023-10-02 16:19 UTC, levBagryansky commented
@yegor256 please take a look

2023-10-03 09:00 UTC, levBagryansky commented
@yegor256 please check

2023-10-03 09:03 UTC, yegor256 commented
@rultor merge

2023-10-03 09:05 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/35354-1744542653)

2023-10-03 09:19 UTC, merged

2023-10-03 09:19 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/35354-1744542653) (took me 14min)