Portal is not in tuple anymore
objectionary/eo pull request #2581
Opened 2023-11-10 13:59 UTC by levBagryansky

2023-11-10 14:39 UTC, maxonfjvipon requested changes
@levBagryansky good one. Just one comment from my side

2023-11-10 14:39 UTC, maxonfjvipon commented on eo-runtime/src/test/eo/org/eolang/rust-tests.eo
>  # @todo #2555:30min Enable rust tests when it's possible to get an abstract object from tuple.
@levBagryansky I think the todo should be removed

2023-11-10 15:57 UTC, maxonfjvipon approved these changes
@levBagryansky LGTM! Thanks

2023-11-10 16:25 UTC, levBagryansky commented
@yegor256 please take a look

2023-11-11 04:19 UTC, yegor256 commented
@rultor merge

2023-11-11 04:21 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/36360-1806672085)

2023-11-11 04:44 UTC, merged

2023-11-11 04:45 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/36360-1806672085) (took me 23min)