#2558: Dataized::take returns byte array
objectionary/eo pull request #2611
Opened 2023-11-21 11:12 UTC by levBagryansky

Closes #2558

2023-11-21 11:32 UTC, levBagryansky commented
@maxonfjvipon please check

2023-11-21 11:52 UTC, maxonfjvipon requested changes

2023-11-21 11:52 UTC, maxonfjvipon commented on eo-runtime/src/main/java/org/eolang/Dataized.java
> +                    "data of must be %s, but was %s",
@levBagryansky you forgot one "%s" here

2023-11-21 13:26 UTC, levBagryansky commented on eo-runtime/src/main/java/org/eolang/Dataized.java
> +                    "data of must be %s, but was %s",
@maxonfjvipon thanks! Done.

2023-11-21 13:49 UTC, maxonfjvipon approved these changes
@levBagryansky LGTM! Thanks

2023-11-21 14:36 UTC, levBagryansky commented
@yegor256 please check

2023-11-22 07:36 UTC, levBagryansky commented
@yegor256 please take a look

2023-11-22 07:40 UTC, yegor256 commented
@rultor merge

2023-11-22 07:42 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/36592-1822255155)

2023-11-22 08:04 UTC, merged

2023-11-22 08:05 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/36592-1822255155) (took me 23min)