#2896: Wait when the test fail
objectionary/eo pull request #2917
Opened 2024-03-04 13:17 UTC by levBagryansky

2024-03-04 19:34 UTC, levBagryansky commented
Pattern :` '.*Errors identified:\s{3}(/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit9699743741109071872/foo/x/main.eo, \d+: .*[\s]*)+\]'`

Actual String to be matched: ` "Optional[14:24:30 [ERROR] com.jcabi.xml.XSLDocument: net.sf.saxon.style.XSLMessage@21baa2ef: Errors identified:\n  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit6068276082387471053/foo/x/main.eo, 2: The alias is invalid: \"THIS-IS-WRONG org.eolang.io.stdout\";\n  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit6068276082387471053/foo/x/main.eo, 2: The alias \"org.eolang.io.stdout\" is not used;\n]"`


Difference in `temp` directory, in pattern and actual:
`junit9699743741109071872,`  pattern  
`junit6068276082387471053` actual
Maybe capturing of logs is not thread safe?

2024-03-05 16:16 UTC, levBagryansky commented
@volodya-lombrozo maybe we can use unique `Logger`s for these tests?

2024-03-05 16:36 UTC, volodya-lombrozo commented
@levBagryansky In this case you might not see the results in your console. The idea is to append "unique" logger appender over the default console logger.

2024-04-15 10:26 UTC, levBagryansky commented
@volodya-lombrozo We should make it the way that `CaptureLogs` gets only messages from it's test. Somehow.

2024-04-15 10:52 UTC, levBagryansky commented
@volodya-lombrozo I have an Idea to do it this way
```
        @Override
        public void append(final LoggingEvent event) {
            if (event.getThreadName().equals(
                Thread.currentThread().getName()
            )) {
                this.logs.append(this.getLayout().format(event));
            }
        }
```
But a test can use different threads inside.

2024-04-15 13:44 UTC, levBagryansky commented
@volodya-lombrozo I don't see any option how to distinguish messages from different tests. They can be from different threads and we cannot "tag" them somehow. 
I suggest to change the method `private String waitForMessage(final String message, final Runnable action) ` to the `private String waitForMessage(final Runnable action, final String ... messages)` and to provide `temp` paths in tests. Only messages with `temp` paths are formed in the test.
Looks like it it is enough in our cases.

2024-04-15 14:00 UTC, volodya-lombrozo commented
@levBagryansky Actually it's a good idea, as for me! I mean this "tagging". However, maybe we can use something different, instead of creating temporary folders (I guess it might be rather slow to constantly touch a filesystem)? Maybe we can use 
[ExtensionContext](https://github.com/objectionary/eo/blob/af896acbe9a0c95b30b285b9b791eca1e764fbd8/eo-maven-plugin/src/test/java/org/eolang/maven/log/CaptureLogs.java#L97) in `beforeEach` and `afterEach` methods? This object has `context.getUniqueId()` method which we can use as a tag producer. What do you think?

2024-04-15 14:06 UTC, levBagryansky commented
@volodya-lombrozo Idea with temps is based on the fact that messages with `"Errors identified"` have usually content like 
`"Optional[14:24:30 [ERROR] com.jcabi.xml.XSLDocument: net.sf.saxon.style.XSLMessage@21baa2ef: Errors identified:\n  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit6068276082387471053/foo/x/main.eo, 2: The alias is invalid: \"THIS-IS-WRONG org.eolang.io.stdout\";\n  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit6068276082387471053/foo/x/main.eo, 2: The alias \"org.eolang.io.stdout\" is not used;\n]"`
So in such case we can filter messages via path

2024-04-15 14:39 UTC, volodya-lombrozo commented
@levBagryansky I see. To be honest, I don't like this solution because:
1) We might loose some  logs that don't have a file path in their log message
2) We should specify `@TempDir` for all the tests where we are interested in logs (which is strange, since we already mentioned `@CaptureLogs`)
3) Tests will create  redundant folders all the time, which might lead to slow build time. 

Hence, if we don't have any other option, we might try to implement it as you suggested, but I would suggest to dig a bit dipper and solve the original concurrency problem with log appenders.

2024-04-15 15:26 UTC, levBagryansky commented
@volodya-lombrozo pls review

2024-04-16 08:00 UTC, volodya-lombrozo requested changes

2024-04-16 09:21 UTC, levBagryansky commented on eo-maven-plugin/src/test/java/org/eolang/maven/log/CaptureLogs.java
> + * @todo #2896:90min Logs should contains only messages related to
@volodya-lombrozo done

2024-04-16 09:33 UTC, volodya-lombrozo approved these changes
@levBagryansky Looks good to me. Thank you for your contribution!

2024-04-16 09:58 UTC, levBagryansky commented
@yegor256 Please take a look

2024-04-17 08:50 UTC, levBagryansky commented
@yegor256 please check

2024-04-27 16:50 UTC, levBagryansky commented
@yegor256 please check

2024-04-29 09:36 UTC, levBagryansky commented
@yegor256 please check. I filter the logs by temp path in order to avoid getting messages from other tests.

2024-05-02 08:16 UTC, levBagryansky commented
@yegor256 please check

2024-05-02 11:05 UTC, levBagryansky commented
@yegor256 please merge

2024-05-09 11:46 UTC, levBagryansky commented
@yegor256 please merge

2024-05-09 19:08 UTC, levBagryansky commented
@yegor256 please check

2024-05-09 19:58 UTC, yegor256 commented
@rultor merge

2024-05-09 20:00 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/41085-2103326173)

2024-05-09 20:23 UTC, merged

2024-05-09 20:24 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/41085-2103326173) (took me 22min)