2390
objectionary/eo pull request #3090
Opened 2024-04-14 14:21 UTC by l3r8yJ

@maxonfjvipon @volodya-lombrozo take a look, please 

closes #2390

2024-04-15 08:08 UTC, l3r8yJ commented
@maxonfjvipon @volodya-lombrozo reminder

2024-04-15 08:47 UTC, volodya-lombrozo requested changes
@l3r8yJ Thank you for the contribution! Could you please make this puzzle more understandable? Imagine newcomers joining project: they should understand what's going on and what they have to do to implement this puzzle by reading the puzzle description.

2024-04-15 20:56 UTC, l3r8yJ commented
@volodya-lombrozo I made some clarifications based on your review. Also for better understanding of the term `dirty classes`, can you explain what means `dirty` in this context?

2024-04-16 07:18 UTC, volodya-lombrozo requested changes

2024-04-16 07:18 UTC, volodya-lombrozo commented on eo-maven-plugin/src/main/java/org/eolang/maven/TranspileMojo.java
> +     * @todo #2375:90min. Implement a mechanism for "internal" and "external" classes.
@l3r8yJ, could you please provide more context? Imagine someone opening this issue in the future; they should be able to understand what to do at first glance:

1. I still don't understand why we might need "internal" and "external" classes, or why we need to implement them.
2. Why should "internal" classes be included in the catalog?
3. Which specific catalog are you referring to?
4. Why should "external" classes be placed in a different directory?
5. Are "catalog" and "directory" the same entities in this context?

2024-04-16 07:32 UTC, volodya-lombrozo commented
> @volodya-lombrozo I made some clarifications based on your review. Also for better understanding of the term `dirty classes`, can you explain what means `dirty` in this context?

@l3r8yJ  `dirty` refers to a type of class that was included in a jar during compilation but should not have been included. In other words, they are classes that were added to a jar by mistake.

Example:

Let's imagine a group of developers of the eo-strings library. Perhaps by mistake, they decided to create an [uber-jar](https://stackoverflow.com/questions/11947037/what-is-an-uber-jar-file). So now, the `eo-strings` jar file contains not only Java atoms but also all dependencies (specifically, all the classes from these dependencies), including the `eo-runtime` library. Therefore, we call these classes `dirty` - they are here by mistake and shouldn't be.

Now, imagine you are trying to build another library that uses `eo-strings` and `eo-runtime`. When you compile your library, you will end up in a situation where you have two versions of `eo-runtime`:

```
your-eo-library-dependencies:
-> eo-strings -> eo-runtime:x
-> eo-runtime:y
```

This is a problem that is sometimes hard to identify. So we "clean" these dirty classes, which actually just hides the problem.

2024-04-25 12:18 UTC, l3r8yJ commented
@volodya-lombrozo so, might be this issue can be resolved with some plugin, which will validate project on `uber-jar`? Plugin should be applied to library itself, wdyt? It should exclude such cases

2024-04-25 16:35 UTC, volodya-lombrozo commented
@l3r8yJ, I believe we should have protection on both sides, in our compiler and during the building of libraries. I'm afraid that creating a new plugin might be some sort of [overengineering](https://en.wikipedia.org/wiki/Overengineering). But I like the idea of libraries validation.

2024-11-23 11:39 UTC, maxonfjvipon commented
@l3r8yJ since it's no more relevant I'm closing this one

2024-11-23 11:39 UTC, closed without merging