fix(#3629): fixed broken @as binding
objectionary/eo pull request #3633
Opened 2024-12-10 13:25 UTC by maxonfjvipon

Closes: #3629

2024-12-10 16:32 UTC, maxonfjvipon commented
@yegor256 please check

2024-12-10 16:59 UTC, yegor256 requested changes

2024-12-10 16:59 UTC, yegor256 commented on .github/workflows/mvn.yml
> +      - run: mvn clean install --errors --batch-mode
@maxonfjvipon why?? :)

2024-12-11 05:25 UTC, maxonfjvipon commented
@yegor256 please check

2024-12-11 06:01 UTC, merged

2024-12-11 06:01 UTC, yegor256 commented
@maxonfjvipon thanks!

2024-12-12 00:48 UTC, 0crat commented
@maxonfjvipon Hey there! 👋 Great job on your contribution! You've earned +4 points, which breaks down like this: +4 base, -16 for no code review (ouch!), -4 for only 4 comments, and +20 to keep you motivated. Remember, code reviews and comments are super important – they can boost your points big time! Next time, aim for at least 6 comments and don't forget that code review. Keep those [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) coming, but watch out for the 200 and 800 thresholds. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the good work! Your balance is now [+65](https://www.eolang.org/zerocracy/objectionary-vitals.html). 💪

<!-- Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -16 for the lack of code review; -4 for very few (4) comments; +20 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+65](https://www.eolang.org/zerocracy/objectionary-vitals.html).  -->