Underline Syntax Errors
objectionary/eo pull request #3700
Opened 2024-12-18 15:08 UTC by volodya-lombrozo

In this PR I've made several useful tweaks:

1. Added the posibility to check error messages in unit tests 
2. Udded `UnderlinedMessage` class that underlines syntax errors (tests provide examples)

It's only the first step to make error messages readable (the future steps are described in the new puzzles)

Related to #3332.

2024-12-18 15:09 UTC, volodya-lombrozo commented
@yegor256 Could you have a look, please?

2024-12-18 18:20 UTC, yegor256 commented
@volodya-lombrozo the build is not clean yet, can you take a look?

2024-12-18 18:21 UTC, yegor256 commented
@maxonfjvipon please, check this one

2024-12-18 18:50 UTC, maxonfjvipon requested changes

2024-12-18 18:50 UTC, maxonfjvipon commented on eo-parser/src/test/java/org/eolang/parser/UnderlinedMessageTest.java
> + * @since 0.1
@volodya-lombrozo let's make it `@since 0.50`

2024-12-18 18:50 UTC, maxonfjvipon commented on eo-parser/src/test/java/org/eolang/parser/UnderlinedMessageTest.java
> +    static Stream<Arguments> examples() {
@volodya-lombrozo can the method be `private`?

2024-12-19 09:18 UTC, maxonfjvipon approved these changes
@volodya-lombrozo LGTM

2024-12-19 09:35 UTC, yegor256 requested changes
@volodya-lombrozo very good contribution! a few comments above though

2024-12-19 09:35 UTC, yegor256 commented on eo-parser/src/main/java/org/eolang/parser/ParsingErrors.java
> +        //  It's better to use {@link #recognizer} to get more specific error messages.
@volodya-lombrozo who is `#recognizer`? If I would be the resolver of this puzzle, I would be very puzzled.

2024-12-19 09:35 UTC, yegor256 commented on eo-parser/src/main/java/org/eolang/parser/UnderlinedMessage.java
> + * For example, if you have a message "Problem is here" and you want to underline
@volodya-lombrozo check this out: https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html This is basically HTML. It's a good practice to use `<p>` tags for paragraphs.

2024-12-19 10:09 UTC, volodya-lombrozo commented
@yegor256 Could you have a look one more time, please?

2024-12-19 10:16 UTC, merged

2024-12-19 10:16 UTC, yegor256 commented
@volodya-lombrozo thanks a lot, this is helpful!