feat(#3756): Use a Single Format for All Error Messages
objectionary/eo pull request #3762
Opened 2024-12-25 13:33 UTC by volodya-lombrozo

Created one more class `LocationMessage` that is used as a default error message:
```
[2:0] error: 'Invalid program declaration'
```
It simply adds line and column where an error occured.

___
PS. Now we have two classes `UnderlinedMessage` and `LocationMessage`. They both have the same structure and similar methods. So, we can create an interface for them.
Moreover, we can change their names to `MsgUnderlined` and `MsgLocation`. I haven't done it in this PR in order to keep its size in some borders.
But we can change it during the PR review.

Closes: #3756.

2024-12-25 13:33 UTC, volodya-lombrozo commented
@yegor256 Could you review these changes, please?

2024-12-25 13:53 UTC, yegor256 requested changes
@volodya-lombrozo looks good, just one comment above

2024-12-25 13:53 UTC, yegor256 commented on eo-parser/src/main/java/org/eolang/parser/LocationMessage.java
> +final class LocationMessage {
@volodya-lombrozo maybe `LocatedMessage`? In general, it's not a good idea to have two glued together nouns as a name of a class. It's unclear what is it, a "location" or a "message"? Also, maybe it's better to name them `MsgLocated` and `MsgUnderlined`?

2024-12-26 07:31 UTC, volodya-lombrozo commented
@yegor256 Renamed classes according with your suggestions: https://github.com/objectionary/eo/pull/3762/commits/829f33494917cabc0337112efdb342692c8f299f
Can you have a look one more time, please?

2024-12-26 07:46 UTC, yegor256 approved these changes
LGTM

2024-12-26 07:47 UTC, yegor256 commented
@volodya-lombrozo thanks!

2024-12-26 07:47 UTC, merged

2024-12-26 13:15 UTC, 0crat commented
@yegor256 Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (4) comments; +10 to give you at least something.  Your running balance is [-16](https://www.eolang.org/zerocracy/objectionary-vitals.html).