redid ram object
objectionary/eo pull request #897
Opened 2022-07-20 13:42 UTC by Graur

#684

2022-07-20 14:44 UTC, Graur commented
@yegor256 please, have a look

2022-07-20 16:50 UTC, yegor256 commented
@Graur why can't we make this `ram-slice` object a kid of `ram`?

2022-07-21 14:03 UTC, Graur commented
@yegor256 Sure! I did it, thanks! Please, have a look

2022-07-21 17:23 UTC, yegor256 requested changes
@Graur see above

2022-07-25 13:30 UTC, Graur commented on eo-runtime/src/main/eo/org/eolang/ram.eo
> +  [rho position size] > ram-slice
@yegor256 I have got a problem with getting `ram-slice` parent object. The chain of parents `ram -> slice -> ram-slice -> @` doesn't work as I expected

2022-07-28 09:57 UTC, yegor256 commented
@rultor merge

2022-07-28 09:58 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26361-1197927253)

2022-07-28 10:06 UTC, merged

2022-07-28 10:06 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26361-1197927253) (took me 8min)