list.reduce implemented via recursion, some tests disabled
objectionary/eo pull request #941
Opened 2022-07-27 16:52 UTC by EugeneDar

2022-07-27 17:08 UTC, EugeneDar commented
@yegor256 @Graur check please.

2022-07-27 17:10 UTC, EugeneDar commented
It is important to note that due to the recursive implementation of list.reducei, we had to temporarily disable (wrap to 'nop') some methods in multimap.eo. Because otherwise they would overflow the stack. @yegor256 is this ok?

2022-07-28 08:14 UTC, Graur requested changes
@EugeneDar Good one! Just a few comments below

2022-07-28 08:14 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/collections/list-tests.eo
> +  reducei2. > res!
@EugeneDar This is a typo?

2022-07-28 08:14 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/collections/map-tests.eo
> +      * ((mp.found 1).at 0) ((mp.found "abc").at 0)
@EugeneDar Can we simplify this test?

2022-07-28 08:14 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/collections/map-tests.eo
> +    (((init-mp.with 1 "a").with 3 "c").with 2 "b").with 4 "d" > mp!
@EugeneDar Same here, can we simplify this test?

2022-07-28 08:14 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/collections/map-tests.eo
> +  nop > @
@EugeneDar I think we can get rid of this test, as part of perfomance test

2022-07-28 08:14 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/collections/multimap-tests.eo
> +      * ((mp.found 1).at 0) ((mp.found "abc").length)
@EugeneDar Same here, can we simplify this test?

2022-07-28 08:14 UTC, Graur commented on eo-runtime/src/test/eo/org/eolang/collections/multimap-tests.eo
> +  nop > @
@EugeneDar I think we can get rid of this test, as part of perfomance test

2022-07-28 11:52 UTC, EugeneDar commented on eo-runtime/src/test/eo/org/eolang/collections/list-tests.eo
> +  reducei2. > res!
@Graur you're right, I'll fix it.

2022-07-28 12:47 UTC, EugeneDar commented
@Graur please check again.

2022-07-28 13:43 UTC, EugeneDar commented
@rultor merge

2022-07-28 13:44 UTC, rultor commented
> @rultor merge

@eugenedar Thanks for your request. @yegor256 Please confirm this.

2022-07-28 13:45 UTC, Graur approved these changes

2022-07-28 13:50 UTC, Graur commented
@yegor256 Please, have a look

2022-07-28 15:11 UTC, yegor256 commented
@rultor merge

2022-07-28 18:46 UTC, EugeneDar commented
@rultor hello

2022-07-28 18:46 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26365-1198290362)

2022-07-28 18:47 UTC, rultor commented
> @rultor merge

@eugenedar @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/26365-1198290362) (spent 1min)

```
com.jcraft.jsch.JSchException: socket is not established
```

2022-07-28 18:49 UTC, rultor commented
> @rultor hello

@eugenedar Hi there! I understand a few simple commands: "merge", "deploy", etc. [This page](http://doc.rultor.com/basics.html) explains them briefly. Any questions or bug reports are [welcome](https://github.com/yegor256/rultor/issues). Have fun :)

2022-07-29 09:39 UTC, yegor256 commented
@rultor merge

2022-07-29 09:40 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26365-1199076962)

2022-07-29 09:46 UTC, merged

2022-07-29 09:48 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26365-1199076962) (took me 7min)