878
objectionary/eo pull request #943
Opened 2022-07-27 18:37 UTC by l3r8yJ

fixed

2022-07-28 08:05 UTC, Graur requested changes
@l3r8yJ i don't think we need to inflate this class so much. 
@yegor256 What do you think?

2022-07-28 08:36 UTC, l3r8yJ commented on eo-runtime/pom.xml
> +</project>
@Graur my miss

2022-07-28 08:36 UTC, l3r8yJ commented on eo-runtime/src/main/java/EOorg/EOeolang/EObool$EOwhile.java
> +import org.eolang.*;
@Graur here too

2022-07-28 08:37 UTC, Graur commented
@yegor256 Can you please run checks?

2022-07-28 08:41 UTC, l3r8yJ commented on eo-runtime/pom.xml
> +</project>
@Graur I forgot to mention that Vertices now got no warnings at all

2022-07-28 09:10 UTC, yegor256 commented
@rultor merge

2022-07-28 09:12 UTC, Graur commented
@yegor256 We don't have checks here

2022-07-28 11:17 UTC, yegor256 commented
@rultor merge

2022-07-28 11:18 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26359-1198007567)

2022-07-28 11:19 UTC, rultor commented
> @rultor merge

@l3r8yj @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/26359-1198007567) (spent 57s)

```
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.TaskAdapter.execute (TaskAdapter.java:154)
    at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:292)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform (Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute (Sequential.java:68)
    at net.sf.antcontrib.logic.IfTask.execute (IfTask.java:197)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.TaskAdapter.execute (TaskAdapter.java:154)
    at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:292)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform (Task.java:348)
    at org.apache.tools.ant.Target.execute (Target.java:435)
    at org.apache.tools.ant.Target.performTasks (Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets (Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget (Project.java:1364)
    at org.apache.maven.plugin.antrun.AntRunMojo.execute (AntRunMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
\u001b[0m\u001b[0mcontainer 8c7d955f6ef1327a8a4a8fa598bce56b9b6ffc6eec8206f1d4eb07b69d2a85db is dead
Thu 28 Jul 2022 01:19:38 PM CEST
```

2022-07-28 11:46 UTC, l3r8yJ commented
@yegor256 @Graur well, here is my bad or not?

2022-07-28 11:50 UTC, Graur commented on eo-runtime/pom.xml
> +</project>
@l3r8yJ This one is not fixed yet

2022-07-28 11:50 UTC, l3r8yJ commented
`mvn clean install -Pqulice` says that build successful

<img width="733" alt="image" src="https://user-images.githubusercontent.com/46355873/181497914-a0f380b5-3ba5-4633-bd50-cc6b57e6a87e.png">

2022-07-28 11:52 UTC, Graur commented
@l3r8yJ I think it is just `rultor` failure

2022-07-28 12:18 UTC, yegor256 commented
@rultor merge

2022-07-28 12:19 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26359-1198065414)

2022-07-28 12:20 UTC, rultor commented
> @rultor merge

@l3r8yj @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/26359-1198065414) (spent 55s)

```
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.TaskAdapter.execute (TaskAdapter.java:154)
    at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:292)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform (Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute (Sequential.java:68)
    at net.sf.antcontrib.logic.IfTask.execute (IfTask.java:197)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.TaskAdapter.execute (TaskAdapter.java:154)
    at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:292)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform (Task.java:348)
    at org.apache.tools.ant.Target.execute (Target.java:435)
    at org.apache.tools.ant.Target.performTasks (Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets (Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget (Project.java:1364)
    at org.apache.maven.plugin.antrun.AntRunMojo.execute (AntRunMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
\u001b[0m\u001b[0mcontainer 41ec17a734889c3f38901b56a31de37936a4ff4ba391249f98bcb0a71c4cd40f is dead
Thu 28 Jul 2022 02:20:06 PM CEST
```

2022-07-28 12:57 UTC, l3r8yJ commented on eo-runtime/pom.xml
> +</project>
@Graur could you give some advice how to fix it or smth?

2022-07-28 13:42 UTC, Graur commented
@l3r8yJ I think the main reason is: 
```
Invalid XML formatting in /eo-runtime/pom.xml
```

2022-07-28 13:48 UTC, l3r8yJ commented
@Graur yes, i've pasted `/eo-runtime/pom.xml` from master into my branch, they are the same. That means we got `Invalid XML formatting` in master or i didn't understand?

2022-07-28 14:59 UTC, l3r8yJ commented
@yegor256 copied from master and fixed `eo/pom.xml` & `eo/eo-runtime/pom.xml` by `xcop`

2022-07-29 09:04 UTC, Graur commented
@l3r8yJ I don't think you should fix `pom.xml` here. Just fix [Vertices.java](https://github.com/objectionary/eo/pull/943/files#diff-a61a8a37ae2b486bbb6cb2d1ccd2faca8543395b20004d48e27efad2c69f918d)

2022-07-29 09:38 UTC, l3r8yJ commented
@Graur my old `pom.xml` broke `rultor merge` because there was a missing EOL at the end of the file, now it's same as master

2022-07-29 09:44 UTC, l3r8yJ commented
@Graur check please, now it's alright?

2022-07-29 10:02 UTC, Graur requested changes
@l3r8yJ Much better! Just a few comments below:

2022-07-29 10:26 UTC, l3r8yJ commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static boolean canToString(final Object obj) {
@Graur maybe just `primitive()`? or it would be better with `is`?

2022-07-29 10:37 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static boolean canToString(final Object obj) {
@l3r8yJ Yes, it is good

2022-07-29 10:37 UTC, l3r8yJ commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static String labelByInstanceOf(final Object obj) {
@Graur i think that we should separate these two methods:

1. We have methods smaller in size.
2. And we know that `labelByInstaceOf()` returns label in specific cases, when `label()` always returns a result.

what do you think?

2022-07-29 10:40 UTC, l3r8yJ commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static String labelFrom(final Object obj) {
@Graur done

2022-07-29 10:41 UTC, l3r8yJ commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static boolean nonNumeric(final Object obj) {
@Graur done

2022-07-29 10:41 UTC, l3r8yJ commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static boolean canToString(final Object obj) {
@Graur done

2022-07-29 10:54 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static boolean canToString(final Object obj) {
@l3r8yJ When it's done it would be better to use `Resolve` button

2022-07-29 11:12 UTC, l3r8yJ commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static String labelByInstanceOf(final Object obj) {
@Graur well, we're merging methods into one or they should stay as they are?

2022-07-29 12:04 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Vertices.java
> +    private static String labelByInstanceOf(final Object obj) {
@l3r8yJ Let's get rid of it

2022-07-29 12:21 UTC, l3r8yJ commented
@Graur ready to merge

2022-07-29 12:24 UTC, Graur approved these changes

2022-07-29 12:24 UTC, Graur commented
@yegor256 please, run workflow checks

2022-07-29 12:35 UTC, Graur approved these changes

2022-07-29 12:35 UTC, Graur commented
@yegor256 Please, have a look

2022-07-29 12:38 UTC, yegor256 commented
@rultor merge

2022-07-29 12:45 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26359-1199229959)

2022-07-29 12:51 UTC, merged

2022-07-29 12:51 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26359-1199229959) (took me 6min)

2022-07-29 12:54 UTC, yegor256 commented
@l3r8yJ thanks!