#942 tried to convert 0.0.as-bytes to -0.0.as-bytes
objectionary/eo pull request #957
Opened 2022-07-29 13:12 UTC by maxonfjvipon

Closes: #942

2022-07-29 13:21 UTC, yegor256 commented
@Graur maybe it's better to use `assert-that` here?

2022-07-29 13:40 UTC, maxonfjvipon commented
@yegor256 it'll be `assert-that` here, ofc, it's just a draft. I'm trying to understand now why `map` and `multimap` tests fail

2022-07-29 13:43 UTC, yegor256 commented
@maxonfjvipon to me the code looks correct. but I may be missing something

2022-07-29 13:44 UTC, maxonfjvipon commented
@maxonfjvipon to me either. But
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/37025995/181773483-5a362889-7dd4-4219-b7ae-1e0daad6655d.png">

2022-07-29 13:56 UTC, maxonfjvipon commented
@yegor256 @Graur ideas or guesses are welcome :)

2022-07-29 14:37 UTC, yegor256 commented
@maxonfjvipon can you show the full stacktrace you get from this unit test?

2022-07-29 14:49 UTC, maxonfjvipon commented
@yegor256 
[INFO] Running EOorg.EOeolang.EOcollections.EOmap_of_mapsTest
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.722 s <<< FAILURE! - in EOorg.EOeolang.EOcollections.EOmap_of_mapsTest
Error:  EOorg.EOeolang.EOcollections.EOmap_of_mapsTest.testWorks  Time elapsed: 0.718 s  <<< ERROR!
EOorg.EOeolang.EOerror$ExError: EOorg.EOeolang.EOstringν108782="The argument '.x' is of Java type 'java.lang.Double', not 'java.lang.Long' as expected"SF
	at org.eolang.PhSafe.attr(PhSafe.java:97)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhImmovable.attr(PhImmovable.java:85)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.Dataized.take(Dataized.java:80)
	at EOorg.EOeolang.EObool$EOor.lambda$new$0(EObool$EOor.java:67)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:241)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhImmovable.attr(PhImmovable.java:85)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:242)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhImmovable.attr(PhImmovable.java:85)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.take(Data.java:116)
	at org.eolang.PhOnce.copy(PhOnce.java:81)
	at org.eolang.PhLocated.copy(PhLocated.java:84)
	at org.eolang.Data$Once.take(Data.java:116)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.take(Data.java:116)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.take(Data.java:116)
	at org.eolang.PhOnce.equals(PhOnce.java:61)
	at org.eolang.PhWith.equals(PhWith.java:32)
	at org.eolang.AtFree.get(AtFree.java:103)
	at org.eolang.AtNamed.get(AtNamed.java:95)
	at org.eolang.AtSafe.get(AtSafe.java:69)
	at EOorg.EOeolang.EObool$EOif.lambda$new$0(EObool$EOif.java:64)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:241)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhImmovable.attr(PhImmovable.java:85)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:242)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhImmovable.attr(PhImmovable.java:85)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhSafe.attr(PhSafe.java:94)
	at org.eolang.PhImmovable.attr(PhImmovable.java:85)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.take(Data.java:116)
	at org.eolang.PhOnce.copy(PhOnce.java:81)
	at org.eolang.PhLocated.copy(PhLocated.java:84)
	a [...]

2022-07-29 15:59 UTC, Graur commented
@maxonfjvipon I think the main problem is when the `key` of the map is `0`. Try this short example:
```
[] > map-with-zero-key
  (map *).with 0 2 > m
  assert-that > @
    (m.found 0).at 0
    $.equal-to 2
```
it should fail.

2022-07-29 19:08 UTC, maxonfjvipon commented
@Graur id doesn't and I think it shouldn't. There is no any special about this zero-key. Your test also works fine.
<img width="483" alt="Screen Shot 2022-07-29 at 10 01 39 PM" src="https://user-images.githubusercontent.com/37025995/181827590-8b5344aa-0093-4315-a354-68879995160d.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/37025995/181828041-bce40ea5-8c97-4eff-993d-9a0a9b90fb0b.png">

2022-07-30 09:39 UTC, maxonfjvipon commented
@yegor256 @Graur is there a way I can see what object has this attribute/argument `x` of wrong type? Mb somewhere in xmir?
<img width="821" alt="image" src="https://user-images.githubusercontent.com/37025995/181904658-b592b472-5d85-46d1-8d6f-3a241daf16c4.png">

2022-07-30 13:03 UTC, maxonfjvipon commented
@Graur @yegor256 so, I found out that the exception is thrown is `strong` method of `Param` class when the argument of the method is `Long.class`. I found that there are 3 places where this method is called with `Long.class` argument and only in one place exception is thrown - `EOint$EOgt`.

I put changes into `strong` method
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/37025995/181914991-52c84a85-773e-4fa0-8eee-bfb8b6a71b7c.png">

I found that the argument we try compare int to is `0.0`. So `some-int.gt 0.0` and here exception is thrown.

Here's phi term:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/37025995/181915153-a6bff82d-03cc-44f8-befb-adea1eb188a3.png">

Here is our `-1` from `map-of-maps` test.
```
...
eq. > @
    list
      * 0 "d"
    * ((mp-res.found -1).length) ((((mp-res.found 1).at 0).found "c").at 0)
```

`-1.as-hash` is 0. There are not so many places where `0.eq 0.0` is possible - all of them is `number`. Please not that we haven't merged [this one](https://github.com/objectionary/eo-math/pull/32) yet. It means that there is a mistake in `number` object that `eo-runtime` loads on tests. 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/37025995/181915427-e2758ded-cb0e-4770-bb5e-3ec52fed9cd0.png">

`map` and `multimap` in their `found` methods call `number.mod` object. `number.mod` calls `number.abs` and in `number.abs` we have:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/37025995/181915477-73d1cbde-ce17-4d9f-ae7c-f5a3384b675c.png">

`-1.as-hash` is 0. `0.is-int` should be `TRUE`, but it's `FALSE` now because of mistake in `number`. So then we go to: `0.gte 0.0` and here's our exception.

I'm not sure I'm right but it seems we should merge [this one](https://github.com/objectionary/eo-math/pull/32), add it to `objectionary` and then try here again.

2022-08-09 13:28 UTC, maxonfjvipon commented
@yegor256 @Graur could you please take a look what's wrong?

2022-08-11 14:21 UTC, Graur commented
@maxonfjvipon Now all checks should pass, please try it

2022-08-11 15:39 UTC, maxonfjvipon commented
@Graur something's wrong with maven-plugin tests

2022-08-11 18:35 UTC, Graur commented
@maxonfjvipon Indeed, it was another checkstyle problem. Please, try it one more time

2022-08-11 18:53 UTC, maxonfjvipon commented
@Graur @yegor256 Hallelujah!
I think it's good to merge

2022-08-12 10:32 UTC, Graur requested changes
@maxonfjvipon Good one, just one comment from my side

2022-08-12 10:32 UTC, Graur commented on eo-runtime/src/main/java/org/eolang/Param.java
> +     * @param obj  The object to fetch the attribute from
@maxonfjvipon I think we can get rid of this change

2022-08-12 11:01 UTC, maxonfjvipon commented
@Graur I hope now it's good to merge

2022-08-12 11:01 UTC, Graur approved these changes
@maxonfjvipon Agree
@yegor256 please, have a look

2022-08-15 14:28 UTC, Graur commented
@yegor256 Could you check these changes, please?

2022-08-15 14:30 UTC, yegor256 commented
@rultor merge

2022-08-15 14:31 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26520-1215079396)

2022-08-15 14:37 UTC, merged

2022-08-15 14:38 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26520-1215079396) (took me 7min)